### ISSUE TITLE
Changing blockquote font size?

### ISSUE THREAD

**Issue by danawoodman** [alanshaw/markdown-pdf#137]
I am unable to apply CSS to blockquotes to change their size, how can this be done?

I've tried:

```css
blockquote { font-size: 20px; }
```

And it is still the default of around 11px.
