### ISSUE TITLE
CJK fonts support to pdf

### ISSUE THREAD

**Issue by rickywu** [alanshaw/markdown-pdf#149]
The output only contains number and alphabetic, Chinese, Japanese, Korean characters missed

My md file is utf-8 encoding.

**Comment by akaustel** [comment]
I'm late to help you out, but just fixed loading a custom font using only stylesheets like this:

```css
/* pdfstyle.css */
@import url('https://fonts.googleapis.com/css?family=Pontano+Sans');

html {
    font-family: 'Pontano Sans';
}
```

and

```javascript
markdownpdf({
  cssPath: __dirname + '/pdfstyle.css',
  paperBorder: '1cm',
  ...
})...
```
