### ISSUE TITLE
Cannot copy text inside PDF?!

### ISSUE THREAD

**Issue by Alwinator** [alanshaw/markdown-pdf#193]
The text inside the PDF is not select-able and not copy-able.
This is because I used a custom font (Open Sans). Is it possible to make the text select-able and copy-able with a custom font?

My CSS code:
```css
@import url('https://fonts.googleapis.com/css2?family=Open+Sans:wght@300;400&display=swap');

span, p, h1, h2, h3, h4, h5, h6, td, th, li {
    font-family: 'Open Sans', sans-serif;
}

```
