### ISSUE TITLE
Pagebreak-Support

### ISSUE THREAD

**Issue by Suven** [alanshaw/markdown-pdf#60]
Hi,

does anybody know how to get pagebreaks working?

I tried to enable custom html in remarkable and then add a css-rule like:

```css
pagebreak {
  page-break-before: always;
  break-before: always;
}
```

Any other ideas?

**Comment by Suven** [comment]
Ah nevermind.. It works on block-elements.

The following DOES work.

```css
pagebreak {
  display: block;
  page-break-before: always;
  break-before: always;
}
```

**Comment by Kabouik** [comment]
I know this issue was closed 5 years ago, but I'm new to `markdown-pdf` and I didn't understand how to make this work with a custom css theme. The command I am using is `markdown-pdf test.md -o test.pdf --css-path ~/.config/markdown-css-themes/mytheme.css`

My css theme contains:
```css
.pagebreak
{
    display: block;
    page-break-after: always;
}
```

My markdown file contains:
```html
<div class="pagebreak"></div>
```

But the rendered PDF file shows this line instead of inserting a pagebreak. Is there something I am forgetting?
