### ISSUE TITLE
Literal URLs should be rendered once 

### ISSUE THREAD

**Issue by chdsbd** [alanshaw/markdown-pdf#93]
Literal URLs in a markdown file will be rendered twice.

\<http://example.com> is rendered as http://example.com (http://example.com)

This seems redundant.

**Comment by anko** [comment]
I agree.

This happens because the URL in parentheses is added [using CSS](https://github.com/alanshaw/markdown-pdf/blob/05985b3431e7c6117ce1c24c33421ab6b1a0b589/html5bp/css/main.css#L246-L248) to any `<a href="something">`.

Implementation idea: Drop the CSS. Instead use [remark](https://github.com/wooorm/remark) to parse the markdown into [mdast](https://github.com/wooorm/mdast), transform Link nodes into Link nodes (followed by Text nodes with the href-in-parentheses if the `title` and `url` differ), render the tree to HTML again, render to PDF as usual.

**Comment by Zadagu** [comment]
I builded a workaround.
Create a custom CSS file:
```css
@media print {
    a[href]:after {
        content: "" !important;
    }

    abbr[title]:after {
        content: " " !important;
    } 
    body {
        font-size: 0.625em;
    }

}
```
Include this file via options.cssPath in js, or via --css-path in shell.
